title: Fundamental
author:
  name: Theo Messenger-Jones
  github: theomjones
  twitter: theomjones

# If you don't have a favicon, change to false.
favicon: true

baseurl: "/fundamental" # Use if your site will be located in a subdirectory, e.g. /blog.
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: Fundamental is a lightweight Jekyll theme.

# Build settings
markdown: kramdown
theme: fundamental


# Enable compononents
enabled:
  breadcrumbs: true
  tags: true
  # Enable RSS menu item
  rss: false
  seo: true

#Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

# Compress Sass for production.
# sass:
  # style: compressed

# Specifying front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "Theo"

#######
#PLUGIN CONFIG
#######

permalink: pretty

# Archives
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
