# REMEMBER TO GO THROUGH THIS FILE, PERSONALISING THE SETTINGS

title: Your Title
author:
  name: Your Name
  github: username
  twitter: username

# If you don't have a favicon, change to false.
favicon: true

footer:
  separator: '|'
  content: Ⓒ Your Name Here
  year: true

baseurl: "" # Use if your site will be located in a subdirectory, e.g. /blog.
url: "" # the base hostname & protocol for your site, e.g. http://example.com

description: Your site description.

# Build settings
markdown: kramdown
theme: fundamental


# Enable compononents
enabled:
  breadcrumbs: true
  tags: true
  # Enable RSS menu item
  rss: false
  seo: true
  # Share buttons are only on desktop (user use the share menu on mobile).
  social:
    enabled: true
    twitter: true
    facebook: true
    messenger: true
    whatsapp: true

socialBtnsColor: '#4845DF'

#Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

# Compress Sass for production.
sass:
  style: compressed

# Specifying front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "YOUR NAME"

#######
#PLUGIN CONFIG
#######

permalink: pretty

# Archives
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
